sonar.projectKey=AppPIN_devops
sonar.organization=josedevops1978-design

sonar.sources=backend/src
sonar.tests=backend/tests

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info