global:
  scrape_interval: 15s # Tiempo entre cada recolección de métricas

scrape_configs:
  # Monitoreo del propio servidor Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoreo del Sistema Operativo de tu Debian
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Monitoreo del Backend en Node.js (Descomentado y corregido)
  - job_name: 'nodejs-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend-gestion-usuarios:3000']

  # Monitoreo de MySQL
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']
